name: Build Docker Image

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=false
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/loggie
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-,enable=${{ github.ref_type == 'branch' }}
            type=ref,event=tag
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
